name: Generate manifest

on:
  push:
    paths:
      - data.json
  workflow_dispatch:

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y jq

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate manifest
        run: ./tools/generate_manifest.sh

      - name: Commit and push manifests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add manifest/*
          if ! git diff --cached --quiet; then
            git commit -m "Update manifest files"
            git push origin "$BRANCH_NAME"
          else
            echo "No changes in manifest to commit"
          fi
